### ISSUE TITLE
`RedshiftSpectrum`'s `endpoint_url` credential doesn't work

### ISSUE THREAD

**Issue by marcinpurtak** [dyvenia/viadot#1098]
When working locally, we need to handle `endpoint_url` within aws credentials.

Currently `endpoint_url` is obtained from `credentials` in 

https://github.com/dyvenia/viadot/blob/7fe5e53e7800b462ff4cc5d013c418acaac33e9d/src/viadot/sources/redshift_spectrum.py#L104

However it don't get to the right place in awswrangler as even when put in the credentials dict, it still produces this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2146, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/viadot/orchestration/prefect/tasks/redshift_spectrum.py", line 73, in df_to_redshift_spectrum
    rs.from_df(
  File "/usr/local/lib/python3.10/site-packages/viadot/sources/redshift_spectrum.py", line 206, in from_df
    wr.s3.to_parquet(
  File "/usr/local/lib/python3.10/site-packages/awswrangler/_config.py", line 542, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_write_parquet.py", line 667, in to_parquet
    paths, partitions_values = _to_dataset(
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_write_dataset.py", line 236, in _to_dataset
    paths, partitions_values = _to_partitions(
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_write_dataset.py", line 122, in _to_partitions
    delete_objects(
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_delete.py", line 139, in delete_objects
    paths: List[str] = _path2list(
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_list.py", line 31, in _path2list
    paths: List[str] = [
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_list.py", line 31, in <listcomp>
    paths: List[str] = [
  File "/usr/local/lib/python3.10/site-packages/awswrangler/s3/_list.py", line 113, in _list_objects
    for page in response_iterator:  # pylint: disable=too-many-nested-blocks
  File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: User: arn:aws:iam::<redacted> is not authorized to perform: s3:ListBucket on resource: "arn:aws:s3:::<redacted>" with an explicit deny in a resource-based policy`

**Comment by marcinpurtak** [comment]
Seems like it works good after adding `endpoint_url` to the AWS Secrets Manager = redshifspectrumsecret
